version: '3.8'
services:
  dyma-postgresql:
    image: postgres:15
    container_name: dyma-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  dyma-pgadmin:
    image: dpage/pgadmin4
    container_name: dyma-pgadmin4
    ports:
      - '8888:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
